/* eslint-disable no-console */
const { PrismaPg } = require("@prisma/adapter-pg");
const { PrismaClient } = require("@prisma/client");

const connectionString = process.env.DIRECT_URL || process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error("Missing DIRECT_URL or DATABASE_URL in environment.");
}

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

// Helper to build a stable picsum image URL per university slug
function img(slug) {
  return `https://picsum.photos/seed/${slug}/800/500`;
}

const universities = [
  // ─── BANGLADESH · PUBLIC ───────────────────────────────────────
  {
    slug: "university-of-dhaka",
    name: "University of Dhaka",
    type: "PUBLIC",
    country: "Bangladesh",
    city: "Dhaka",
    bannerImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1400&q=80",
    websiteUrl: "https://www.du.ac.bd",
    description: "Bangladesh's oldest and most prestigious public university founded in 1921, renowned for humanities, sciences, and law.",
  },
  {
    slug: "bangladesh-university-of-engineering-and-technology",
    name: "Bangladesh University of Engineering and Technology",
    type: "PUBLIC",
    country: "Bangladesh",
    city: "Dhaka",
    bannerImageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1400&q=80",
    websiteUrl: "https://www.buet.ac.bd",
    description: "Leading engineering and technology-focused public university in Bangladesh, producing top engineers since 1962.",
  },
  {
    slug: "jahangirnagar-university",
    name: "Jahangirnagar University",
    type: "PUBLIC",
    country: "Bangladesh",
    city: "Savar",
    state: "Dhaka Division",
    bannerImageUrl: img("jahangirnagar-university"),
    websiteUrl: "https://juniv.edu",
    description: "Residential public university in Savar with a scenic campus and strong programs in social sciences and natural sciences.",
  },
  {
    slug: "rajshahi-university",
    name: "Rajshahi University",
    type: "PUBLIC",
    country: "Bangladesh",
    city: "Rajshahi",
    bannerImageUrl: img("rajshahi-university"),
    websiteUrl: "https://www.ru.ac.bd",
    description: "Major public university in northern Bangladesh offering comprehensive undergraduate and postgraduate programs.",
  },
  {
    slug: "khulna-university",
    name: "Khulna University",
    type: "PUBLIC",
    country: "Bangladesh",
    city: "Khulna",
    bannerImageUrl: img("khulna-university"),
    websiteUrl: "https://ku.ac.bd",
    description: "Public university in Khulna specialising in architecture, business administration, and natural sciences.",
  },
  {
    slug: "shahjalal-university-of-science-and-technology",
    name: "Shahjalal University of Science and Technology",
    type: "PUBLIC",
    country: "Bangladesh",
    city: "Sylhet",
    bannerImageUrl: img("shahjalal-university-sust"),
    websiteUrl: "https://www.sust.edu",
    description: "Science and technology focused public university in Sylhet, known for computer science and engineering programs.",
  },
  {
    slug: "bangladesh-agricultural-university",
    name: "Bangladesh Agricultural University",
    type: "PUBLIC",
    country: "Bangladesh",
    city: "Mymensingh",
    bannerImageUrl: img("bangladesh-agricultural-university"),
    websiteUrl: "https://www.bau.edu.bd",
    description: "Premier agricultural research and teaching institution in Bangladesh serving the nation since 1961.",
  },
  {
    slug: "comilla-university",
    name: "Comilla University",
    type: "PUBLIC",
    country: "Bangladesh",
    city: "Comilla",
    bannerImageUrl: img("comilla-university"),
    websiteUrl: "https://cou.ac.bd",
    description: "Public university in Comilla offering programs in business, social sciences, engineering, and the arts.",
  },
  {
    slug: "noakhali-science-and-technology-university",
    name: "Noakhali Science and Technology University",
    type: "PUBLIC",
    country: "Bangladesh",
    city: "Noakhali",
    bannerImageUrl: img("noakhali-science-and-technology-university"),
    websiteUrl: "https://nstu.edu.bd",
    description: "Public science and technology university in coastal Noakhali with focus on applied sciences and environmental studies.",
  },

  // ─── BANGLADESH · PRIVATE ──────────────────────────────────────
  {
    slug: "north-south-university",
    name: "North South University",
    type: "PRIVATE",
    country: "Bangladesh",
    city: "Dhaka",
    bannerImageUrl: "https://images.unsplash.com/photo-1568792923760-d70635a89fdc?auto=format&fit=crop&w=1400&q=80",
    websiteUrl: "http://www.northsouth.edu",
    description: "One of Bangladesh's top private universities with modern facilities, global partnerships, and a strong business school.",
  },
  {
    slug: "brac-university",
    name: "BRAC University",
    type: "PRIVATE",
    country: "Bangladesh",
    city: "Dhaka",
    bannerImageUrl: img("brac-university"),
    websiteUrl: "https://www.bracu.ac.bd",
    description: "Award-winning private university in Dhaka affiliated with BRAC, known for liberal arts, architecture, and development studies.",
  },
  {
    slug: "independent-university-bangladesh",
    name: "Independent University Bangladesh",
    type: "PRIVATE",
    country: "Bangladesh",
    city: "Dhaka",
    bannerImageUrl: img("independent-university-bangladesh"),
    websiteUrl: "https://iub.edu.bd",
    description: "Research-oriented private university in Dhaka offering programs in business, computer science, and environmental science.",
  },
  {
    slug: "east-west-university",
    name: "East West University",
    type: "PRIVATE",
    country: "Bangladesh",
    city: "Dhaka",
    bannerImageUrl: img("east-west-university"),
    websiteUrl: "https://ewubd.edu",
    description: "Private university in Dhaka with strong emphasis on applied sciences, business, and English language education.",
  },
  {
    slug: "american-international-university-bangladesh",
    name: "American International University-Bangladesh",
    type: "PRIVATE",
    country: "Bangladesh",
    city: "Dhaka",
    bannerImageUrl: img("aiub-dhaka"),
    websiteUrl: "https://www.aiub.edu",
    description: "US-affiliated private university in Dhaka offering American-style education with a strong focus on engineering and business.",
  },
  {
    slug: "ahsanullah-university-of-science-and-technology",
    name: "Ahsanullah University of Science and Technology",
    type: "PRIVATE",
    country: "Bangladesh",
    city: "Dhaka",
    bannerImageUrl: img("ahsanullah-university-aust"),
    websiteUrl: "https://aust.edu",
    description: "Private engineering university in Dhaka founded by the Ahsania Mission, specialising in engineering and architecture.",
  },
  {
    slug: "daffodil-international-university",
    name: "Daffodil International University",
    type: "PRIVATE",
    country: "Bangladesh",
    city: "Dhaka",
    bannerImageUrl: img("daffodil-international-university"),
    websiteUrl: "https://daffodilvarsity.edu.bd",
    description: "Technology-driven private university in Bangladesh with a purpose-built campus and digital innovation focus.",
  },
  {
    slug: "united-international-university",
    name: "United International University",
    type: "PRIVATE",
    country: "Bangladesh",
    city: "Dhaka",
    bannerImageUrl: img("united-international-university"),
    websiteUrl: "https://www.uiu.ac.bd",
    description: "Private university in Dhaka with state-of-the-art labs and programs in CSE, EEE, and business administration.",
  },
  {
    slug: "southeast-university-dhaka",
    name: "Southeast University",
    type: "PRIVATE",
    country: "Bangladesh",
    city: "Dhaka",
    bannerImageUrl: img("southeast-university-dhaka"),
    websiteUrl: "https://seu.edu.bd",
    description: "Private university in Dhaka offering quality programs in engineering, law, and business management.",
  },
  {
    slug: "university-of-liberal-arts-bangladesh",
    name: "University of Liberal Arts Bangladesh",
    type: "PRIVATE",
    country: "Bangladesh",
    city: "Dhaka",
    bannerImageUrl: img("ulab-dhaka"),
    websiteUrl: "https://ulab.edu.bd",
    description: "Bangladesh's first liberal arts–focused private university, renowned for media studies, design, and humanities.",
  },

  // ─── BANGLADESH · NATIONAL ─────────────────────────────────────
  {
    slug: "islamic-university-bangladesh",
    name: "Islamic University Bangladesh",
    type: "NATIONAL",
    country: "Bangladesh",
    city: "Kushtia",
    bannerImageUrl: img("islamic-university-kushtia"),
    websiteUrl: "https://iu.ac.bd",
    description: "National university in Kushtia offering programs in Islamic studies, law, and social sciences.",
  },
  {
    slug: "bangladesh-open-university",
    name: "Bangladesh Open University",
    type: "NATIONAL",
    country: "Bangladesh",
    city: "Gazipur",
    bannerImageUrl: img("bangladesh-open-university"),
    websiteUrl: "https://www.bou.ac.bd",
    description: "National distance-learning university offering flexible programs to learners across Bangladesh.",
  },
  {
    slug: "university-of-chittagong",
    name: "University of Chittagong",
    type: "NATIONAL",
    country: "Bangladesh",
    city: "Chittagong",
    bannerImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1400&q=80",
    websiteUrl: "https://www.cu.ac.bd",
    description: "Major national university in Bangladesh with broad undergraduate and graduate offerings in arts, science, and commerce.",
  },

  // ─── USA · INTERNATIONAL ───────────────────────────────────────
  {
    slug: "harvard-university",
    name: "Harvard University",
    type: "INTERNATIONAL",
    country: "USA",
    city: "Cambridge",
    state: "Massachusetts",
    bannerImageUrl: img("harvard-university"),
    websiteUrl: "https://www.harvard.edu",
    description: "World's most prestigious university, founded in 1636, excelling in law, medicine, business, and the sciences.",
  },
  {
    slug: "massachusetts-institute-of-technology",
    name: "Massachusetts Institute of Technology",
    type: "INTERNATIONAL",
    country: "USA",
    city: "Cambridge",
    state: "Massachusetts",
    bannerImageUrl: img("mit-cambridge"),
    websiteUrl: "https://www.mit.edu",
    description: "World-leading research institution in science, technology, engineering, and mathematics with unmatched innovation culture.",
  },
  {
    slug: "stanford-university",
    name: "Stanford University",
    type: "INTERNATIONAL",
    country: "USA",
    city: "Stanford",
    state: "California",
    bannerImageUrl: img("stanford-university"),
    websiteUrl: "https://www.stanford.edu",
    description: "Elite research university in Silicon Valley renowned for entrepreneurship, engineering, and business excellence.",
  },
  {
    slug: "yale-university",
    name: "Yale University",
    type: "INTERNATIONAL",
    country: "USA",
    city: "New Haven",
    state: "Connecticut",
    bannerImageUrl: img("yale-university"),
    websiteUrl: "https://www.yale.edu",
    description: "Ivy League university with outstanding programs in law, arts, drama, international studies, and the natural sciences.",
  },
  {
    slug: "columbia-university",
    name: "Columbia University",
    type: "INTERNATIONAL",
    country: "USA",
    city: "New York",
    state: "New York",
    bannerImageUrl: img("columbia-university"),
    websiteUrl: "https://www.columbia.edu",
    description: "Ivy League research university in the heart of New York City, renowned for journalism, law, and international affairs.",
  },
  {
    slug: "university-of-california-berkeley",
    name: "University of California, Berkeley",
    type: "INTERNATIONAL",
    country: "USA",
    city: "Berkeley",
    state: "California",
    bannerImageUrl: img("uc-berkeley"),
    websiteUrl: "https://www.berkeley.edu",
    description: "Flagship UC campus and global public research leader with top-ranked programs in tech, law, and social sciences.",
  },
  {
    slug: "princeton-university",
    name: "Princeton University",
    type: "INTERNATIONAL",
    country: "USA",
    city: "Princeton",
    state: "New Jersey",
    bannerImageUrl: img("princeton-university"),
    websiteUrl: "https://www.princeton.edu",
    description: "Ivy League university renowned for its undergraduate focus, mathematics, physics, public policy, and humanities.",
  },
  {
    slug: "university-of-chicago",
    name: "University of Chicago",
    type: "INTERNATIONAL",
    country: "USA",
    city: "Chicago",
    state: "Illinois",
    bannerImageUrl: img("university-of-chicago"),
    websiteUrl: "https://www.uchicago.edu",
    description: "Research powerhouse celebrated for economics, law, and rigorous interdisciplinary inquiry across all disciplines.",
  },
  {
    slug: "johns-hopkins-university",
    name: "Johns Hopkins University",
    type: "INTERNATIONAL",
    country: "USA",
    city: "Baltimore",
    state: "Maryland",
    bannerImageUrl: img("johns-hopkins-university"),
    websiteUrl: "https://www.jhu.edu",
    description: "Pioneer of the American research university model, globally leading in public health, medicine, and engineering.",
  },
  {
    slug: "university-of-michigan",
    name: "University of Michigan",
    type: "INTERNATIONAL",
    country: "USA",
    city: "Ann Arbor",
    state: "Michigan",
    bannerImageUrl: img("university-of-michigan"),
    websiteUrl: "https://umich.edu",
    description: "Top-ranked public research university known for business, medicine, law, and engineering innovation.",
  },

  // ─── UK · INTERNATIONAL ────────────────────────────────────────
  {
    slug: "university-of-oxford",
    name: "University of Oxford",
    type: "INTERNATIONAL",
    country: "UK",
    city: "Oxford",
    bannerImageUrl: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&w=1400&q=80",
    websiteUrl: "https://www.ox.ac.uk",
    description: "World's oldest English-speaking university with exceptional research across all disciplines since 1096.",
  },
  {
    slug: "university-of-cambridge",
    name: "University of Cambridge",
    type: "INTERNATIONAL",
    country: "UK",
    city: "Cambridge",
    bannerImageUrl: img("university-of-cambridge"),
    websiteUrl: "https://www.cam.ac.uk",
    description: "Ancient collegiate university consistently ranked among the world's best, home to 120+ Nobel laureates.",
  },
  {
    slug: "imperial-college-london",
    name: "Imperial College London",
    type: "INTERNATIONAL",
    country: "UK",
    city: "London",
    bannerImageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1400&q=80",
    websiteUrl: "https://www.imperial.ac.uk",
    description: "World-class institution specialising in science, engineering, medicine, and business with global research impact.",
  },
  {
    slug: "university-college-london",
    name: "University College London",
    type: "INTERNATIONAL",
    country: "UK",
    city: "London",
    bannerImageUrl: img("university-college-london"),
    websiteUrl: "https://www.ucl.ac.uk",
    description: "London's leading multidisciplinary university with strengths in law, architecture, and the biomedical sciences.",
  },
  {
    slug: "london-school-of-economics",
    name: "London School of Economics",
    type: "INTERNATIONAL",
    country: "UK",
    city: "London",
    bannerImageUrl: img("london-school-of-economics"),
    websiteUrl: "https://www.lse.ac.uk",
    description: "World's premier social science institution specialising in economics, political science, and international development.",
  },
  {
    slug: "university-of-edinburgh",
    name: "University of Edinburgh",
    type: "INTERNATIONAL",
    country: "UK",
    city: "Edinburgh",
    bannerImageUrl: img("university-of-edinburgh"),
    websiteUrl: "https://www.ed.ac.uk",
    description: "One of Scotland's ancient universities, world-leading in informatics, medicine, and the humanities.",
  },
  {
    slug: "kings-college-london",
    name: "King's College London",
    type: "INTERNATIONAL",
    country: "UK",
    city: "London",
    bannerImageUrl: img("kings-college-london"),
    websiteUrl: "https://www.kcl.ac.uk",
    description: "Russell Group university in central London renowned for law, dentistry, nursing, and global health research.",
  },
  {
    slug: "university-of-manchester",
    name: "University of Manchester",
    type: "INTERNATIONAL",
    country: "UK",
    city: "Manchester",
    bannerImageUrl: img("university-of-manchester"),
    websiteUrl: "https://www.manchester.ac.uk",
    description: "Research-intensive Russell Group university where graphene was discovered, with world-class engineering and business programs.",
  },
  {
    slug: "university-of-warwick",
    name: "University of Warwick",
    type: "INTERNATIONAL",
    country: "UK",
    city: "Coventry",
    bannerImageUrl: img("university-of-warwick"),
    websiteUrl: "https://warwick.ac.uk",
    description: "Innovative UK university with a strong campus culture, top-ranked business school, and leading STEM research.",
  },

  // ─── AUSTRALIA · INTERNATIONAL ─────────────────────────────────
  {
    slug: "university-of-melbourne",
    name: "University of Melbourne",
    type: "INTERNATIONAL",
    country: "Australia",
    city: "Melbourne",
    bannerImageUrl: "https://images.unsplash.com/photo-1590012314607-cda9d9b699ae?auto=format&fit=crop&w=1400&q=80",
    websiteUrl: "https://www.unimelb.edu.au",
    description: "Australia's top-ranked university offering world-class graduate programs across medicine, law, and engineering.",
  },
  {
    slug: "australian-national-university",
    name: "Australian National University",
    type: "INTERNATIONAL",
    country: "Australia",
    city: "Canberra",
    bannerImageUrl: img("australian-national-university"),
    websiteUrl: "https://www.anu.edu.au",
    description: "Australia's national research university in Canberra with outstanding programs in politics, physics, and international studies.",
  },
  {
    slug: "university-of-sydney",
    name: "University of Sydney",
    type: "INTERNATIONAL",
    country: "Australia",
    city: "Sydney",
    bannerImageUrl: img("university-of-sydney"),
    websiteUrl: "https://www.sydney.edu.au",
    description: "Australia's first university, with a stunning Gothic campus and globally recognised programs in medicine and law.",
  },
  {
    slug: "university-of-queensland",
    name: "University of Queensland",
    type: "INTERNATIONAL",
    country: "Australia",
    city: "Brisbane",
    bannerImageUrl: img("university-of-queensland"),
    websiteUrl: "https://www.uq.edu.au",
    description: "Leading research university in Brisbane ranked in the top 50 globally, excelling in biological sciences and engineering.",
  },
  {
    slug: "monash-university",
    name: "Monash University",
    type: "INTERNATIONAL",
    country: "Australia",
    city: "Melbourne",
    bannerImageUrl: img("monash-university"),
    websiteUrl: "https://www.monash.edu",
    description: "Australia's largest university with campuses across five continents, excelling in pharmacy, business, and engineering.",
  },
  {
    slug: "university-of-new-south-wales",
    name: "University of New South Wales",
    type: "INTERNATIONAL",
    country: "Australia",
    city: "Sydney",
    bannerImageUrl: img("unsw-sydney"),
    websiteUrl: "https://www.unsw.edu.au",
    description: "UNSW Sydney leads Australia in research impact with world-class programs in engineering, business, and law.",
  },
  {
    slug: "university-of-western-australia",
    name: "University of Western Australia",
    type: "INTERNATIONAL",
    country: "Australia",
    city: "Perth",
    bannerImageUrl: img("university-of-western-australia"),
    websiteUrl: "https://www.uwa.edu.au",
    description: "Premier research university in Perth with a beautiful campus, offering strong programs in agriculture and medicine.",
  },
  {
    slug: "university-of-adelaide",
    name: "University of Adelaide",
    type: "INTERNATIONAL",
    country: "Australia",
    city: "Adelaide",
    bannerImageUrl: img("university-of-adelaide"),
    websiteUrl: "https://www.adelaide.edu.au",
    description: "One of Australia's oldest universities in Adelaide, celebrated for agriculture, wine science, and health programs.",
  },

  // ─── CANADA · INTERNATIONAL ────────────────────────────────────
  {
    slug: "university-of-toronto",
    name: "University of Toronto",
    type: "INTERNATIONAL",
    country: "Canada",
    city: "Toronto",
    bannerImageUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1400&q=80",
    websiteUrl: "https://www.utoronto.ca",
    description: "Canada's top research university driving discoveries in AI, medicine, and public policy from downtown Toronto.",
  },
  {
    slug: "university-of-british-columbia",
    name: "University of British Columbia",
    type: "INTERNATIONAL",
    country: "Canada",
    city: "Vancouver",
    bannerImageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?auto=format&fit=crop&w=1400&q=80",
    websiteUrl: "https://www.ubc.ca",
    description: "World-class research university with a stunning Pacific campus, leading in sustainability, forestry, and life sciences.",
  },
  {
    slug: "mcgill-university",
    name: "McGill University",
    type: "INTERNATIONAL",
    country: "Canada",
    city: "Montreal",
    bannerImageUrl: img("mcgill-university"),
    websiteUrl: "https://www.mcgill.ca",
    description: "Canada's most internationally diverse university in Montreal, globally ranked for medicine, law, and humanities.",
  },
  {
    slug: "university-of-alberta",
    name: "University of Alberta",
    type: "INTERNATIONAL",
    country: "Canada",
    city: "Edmonton",
    bannerImageUrl: img("university-of-alberta"),
    websiteUrl: "https://www.ualberta.ca",
    description: "Leading Canadian research university in Edmonton with top-ranked petroleum engineering and environmental studies programs.",
  },
  {
    slug: "mcmaster-university",
    name: "McMaster University",
    type: "INTERNATIONAL",
    country: "Canada",
    city: "Hamilton",
    bannerImageUrl: img("mcmaster-university"),
    websiteUrl: "https://www.mcmaster.ca",
    description: "Innovative university in Hamilton known for problem-based learning and world-leading health sciences research.",
  },
  {
    slug: "university-of-waterloo",
    name: "University of Waterloo",
    type: "INTERNATIONAL",
    country: "Canada",
    city: "Waterloo",
    bannerImageUrl: img("university-of-waterloo"),
    websiteUrl: "https://uwaterloo.ca",
    description: "Canada's tech powerhouse famous for its co-operative education program and partnerships with Google, BlackBerry, and OpenAI.",
  },
  {
    slug: "western-university-canada",
    name: "Western University",
    type: "INTERNATIONAL",
    country: "Canada",
    city: "London",
    state: "Ontario",
    bannerImageUrl: img("western-university-canada"),
    websiteUrl: "https://www.uwo.ca",
    description: "Comprehensive research university in Ontario with top programs in medicine, business, and social sciences.",
  },
  {
    slug: "queens-university-canada",
    name: "Queen's University",
    type: "INTERNATIONAL",
    country: "Canada",
    city: "Kingston",
    state: "Ontario",
    bannerImageUrl: img("queens-university-canada"),
    websiteUrl: "https://www.queensu.ca",
    description: "Historic university in Kingston, Ontario, with exceptional undergraduate programs in engineering, business, and arts.",
  },

  // ─── GERMANY · INTERNATIONAL ───────────────────────────────────
  {
    slug: "technical-university-of-munich",
    name: "Technical University of Munich",
    type: "INTERNATIONAL",
    country: "Germany",
    city: "Munich",
    bannerImageUrl: "https://images.unsplash.com/photo-1519452575417-564c1401ecc0?auto=format&fit=crop&w=1400&q=80",
    websiteUrl: "https://www.tum.de",
    description: "Germany's top technical university in Munich, globally recognised for engineering, natural sciences, and entrepreneurship.",
  },
  {
    slug: "ludwig-maximilian-university-of-munich",
    name: "Ludwig Maximilian University of Munich",
    type: "INTERNATIONAL",
    country: "Germany",
    city: "Munich",
    bannerImageUrl: img("lmu-munich"),
    websiteUrl: "https://www.lmu.de",
    description: "One of Europe's oldest universities with a broad academic portfolio spanning medicine, law, and the humanities.",
  },
  {
    slug: "heidelberg-university",
    name: "Heidelberg University",
    type: "INTERNATIONAL",
    country: "Germany",
    city: "Heidelberg",
    bannerImageUrl: img("heidelberg-university"),
    websiteUrl: "https://www.uni-heidelberg.de",
    description: "Germany's oldest university, celebrated for medical research, natural sciences, and an iconic riverside campus.",
  },
  {
    slug: "free-university-of-berlin",
    name: "Free University of Berlin",
    type: "INTERNATIONAL",
    country: "Germany",
    city: "Berlin",
    bannerImageUrl: img("free-university-berlin"),
    websiteUrl: "https://www.fu-berlin.de",
    description: "Research-intensive university in Berlin with outstanding programs in social sciences, humanities, and life sciences.",
  },
  {
    slug: "humboldt-university-of-berlin",
    name: "Humboldt University of Berlin",
    type: "INTERNATIONAL",
    country: "Germany",
    city: "Berlin",
    bannerImageUrl: img("humboldt-university-berlin"),
    websiteUrl: "https://www.hu-berlin.de",
    description: "Historic university in central Berlin, birthplace of the modern research university model; home to 57 Nobel laureates.",
  },
  {
    slug: "rwth-aachen-university",
    name: "RWTH Aachen University",
    type: "INTERNATIONAL",
    country: "Germany",
    city: "Aachen",
    bannerImageUrl: img("rwth-aachen"),
    websiteUrl: "https://www.rwth-aachen.de",
    description: "Germany's premier technical university in Aachen with world-leading engineering and automotive research programs.",
  },
  {
    slug: "university-of-hamburg",
    name: "University of Hamburg",
    type: "INTERNATIONAL",
    country: "Germany",
    city: "Hamburg",
    bannerImageUrl: img("university-of-hamburg"),
    websiteUrl: "https://www.uni-hamburg.de",
    description: "Major research university in Hamburg with outstanding meteorology, law, and natural sciences departments.",
  },
  {
    slug: "karlsruhe-institute-of-technology",
    name: "Karlsruhe Institute of Technology",
    type: "INTERNATIONAL",
    country: "Germany",
    city: "Karlsruhe",
    bannerImageUrl: img("kit-karlsruhe"),
    websiteUrl: "https://www.kit.edu",
    description: "Elite technical university in Germany merging research and teaching in energy, mobility, and computer science.",
  },

  // ─── FRANCE · INTERNATIONAL ────────────────────────────────────
  {
    slug: "paris-sciences-et-lettres-university",
    name: "Paris Sciences et Lettres University",
    type: "INTERNATIONAL",
    country: "France",
    city: "Paris",
    bannerImageUrl: img("psl-paris"),
    websiteUrl: "https://psl.eu",
    description: "France's top-ranked university combining the Grandes Écoles tradition with world-class research across all disciplines.",
  },
  {
    slug: "ecole-polytechnique",
    name: "École Polytechnique",
    type: "INTERNATIONAL",
    country: "France",
    city: "Palaiseau",
    state: "Île-de-France",
    bannerImageUrl: img("ecole-polytechnique-france"),
    websiteUrl: "https://www.polytechnique.edu",
    description: "France's most elite engineering grande école, producing world leaders in science, technology, and governance.",
  },
  {
    slug: "sorbonne-university",
    name: "Sorbonne University",
    type: "INTERNATIONAL",
    country: "France",
    city: "Paris",
    bannerImageUrl: img("sorbonne-university"),
    websiteUrl: "https://www.sorbonne-universite.fr",
    description: "Storied Parisian university at the heart of European intellectual life, globally ranked in arts, sciences, and medicine.",
  },
  {
    slug: "sciences-po-paris",
    name: "Sciences Po Paris",
    type: "INTERNATIONAL",
    country: "France",
    city: "Paris",
    bannerImageUrl: img("sciences-po-paris"),
    websiteUrl: "https://www.sciencespo.fr",
    description: "World's leading institution for political science, international relations, and public affairs.",
  },
  {
    slug: "university-paris-saclay",
    name: "University of Paris-Saclay",
    type: "INTERNATIONAL",
    country: "France",
    city: "Paris",
    bannerImageUrl: img("paris-saclay"),
    websiteUrl: "https://www.universite-paris-saclay.fr",
    description: "Top French research cluster combining universities and grandes écoles for excellence in STEM fields.",
  },
  {
    slug: "university-of-paris",
    name: "University of Paris",
    type: "INTERNATIONAL",
    country: "France",
    city: "Paris",
    bannerImageUrl: img("university-of-paris"),
    websiteUrl: "https://u-paris.fr",
    description: "Major multidisciplinary university in Paris offering programs in health, social sciences, and exact sciences.",
  },
  {
    slug: "grenoble-alpes-university",
    name: "Grenoble Alpes University",
    type: "INTERNATIONAL",
    country: "France",
    city: "Grenoble",
    bannerImageUrl: img("grenoble-alpes-university"),
    websiteUrl: "https://www.univ-grenoble-alpes.fr",
    description: "Mountain-city research university in Grenoble with world-class programs in physics, nanotechnology, and alpine studies.",
  },
  {
    slug: "university-of-lyon",
    name: "University of Lyon",
    type: "INTERNATIONAL",
    country: "France",
    city: "Lyon",
    bannerImageUrl: img("university-of-lyon"),
    websiteUrl: "https://www.universite-lyon.fr",
    description: "Federated research university in France's gastronomic capital, excelling in chemistry, materials science, and arts.",
  },

  // ─── NETHERLANDS · INTERNATIONAL ───────────────────────────────
  {
    slug: "university-of-amsterdam",
    name: "University of Amsterdam",
    type: "INTERNATIONAL",
    country: "Netherlands",
    city: "Amsterdam",
    bannerImageUrl: "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?auto=format&fit=crop&w=1400&q=80",
    websiteUrl: "https://www.uva.nl",
    description: "Research university in the heart of Amsterdam, globally leading in social sciences, humanities, and data science.",
  },
  {
    slug: "delft-university-of-technology",
    name: "Delft University of Technology",
    type: "INTERNATIONAL",
    country: "Netherlands",
    city: "Delft",
    bannerImageUrl: img("delft-university-technology"),
    websiteUrl: "https://www.tudelft.nl",
    description: "Europe's top technical university in Delft, world-renowned for water management, aerospace, and sustainable design.",
  },
  {
    slug: "leiden-university",
    name: "Leiden University",
    type: "INTERNATIONAL",
    country: "Netherlands",
    city: "Leiden",
    bannerImageUrl: img("leiden-university"),
    websiteUrl: "https://www.leidenuniv.nl",
    description: "The Netherlands' oldest university in Leiden with exceptional strengths in law, medicine, and natural sciences.",
  },
  {
    slug: "utrecht-university",
    name: "Utrecht University",
    type: "INTERNATIONAL",
    country: "Netherlands",
    city: "Utrecht",
    bannerImageUrl: img("utrecht-university"),
    websiteUrl: "https://www.uu.nl",
    description: "The Netherlands' largest university, highly ranked in veterinary science, pharmaceutical sciences, and sustainability.",
  },
  {
    slug: "eindhoven-university-of-technology",
    name: "Eindhoven University of Technology",
    type: "INTERNATIONAL",
    country: "Netherlands",
    city: "Eindhoven",
    bannerImageUrl: img("eindhoven-university-technology"),
    websiteUrl: "https://www.tue.nl",
    description: "Technical university in Eindhoven at the heart of the Dutch Brainport innovation ecosystem, partnering with ASML and Philips.",
  },
  {
    slug: "wageningen-university",
    name: "Wageningen University & Research",
    type: "INTERNATIONAL",
    country: "Netherlands",
    city: "Wageningen",
    bannerImageUrl: img("wageningen-university"),
    websiteUrl: "https://www.wur.nl",
    description: "World's top food and agriculture university driving innovation in sustainable food systems and life sciences.",
  },
  {
    slug: "erasmus-university-rotterdam",
    name: "Erasmus University Rotterdam",
    type: "INTERNATIONAL",
    country: "Netherlands",
    city: "Rotterdam",
    bannerImageUrl: img("erasmus-university-rotterdam"),
    websiteUrl: "https://www.eur.nl",
    description: "Distinguished Rotterdam university home to the world-famous Rotterdam School of Management and an outstanding law school.",
  },
  {
    slug: "radboud-university",
    name: "Radboud University",
    type: "INTERNATIONAL",
    country: "Netherlands",
    city: "Nijmegen",
    bannerImageUrl: img("radboud-university"),
    websiteUrl: "https://www.ru.nl",
    description: "Green-campus university in Nijmegen excelling in molecular life sciences, medical imaging, and cognitive neuroscience.",
  },

  // ─── SWEDEN · INTERNATIONAL ────────────────────────────────────
  {
    slug: "lund-university",
    name: "Lund University",
    type: "INTERNATIONAL",
    country: "Sweden",
    city: "Lund",
    bannerImageUrl: "https://images.unsplash.com/photo-1613909207039-6b173b755cc1?auto=format&fit=crop&w=1400&q=80",
    websiteUrl: "https://www.lunduniversity.lu.se",
    description: "Sweden's most internationally recognised university; top-ranked in Scandinavia for medicine, engineering, and sustainability.",
  },
  {
    slug: "kth-royal-institute-of-technology",
    name: "KTH Royal Institute of Technology",
    type: "INTERNATIONAL",
    country: "Sweden",
    city: "Stockholm",
    bannerImageUrl: img("kth-stockholm"),
    websiteUrl: "https://www.kth.se",
    description: "Scandinavia's leading technical university driving innovation in ICT, transport, energy, and the built environment.",
  },
  {
    slug: "uppsala-university",
    name: "Uppsala University",
    type: "INTERNATIONAL",
    country: "Sweden",
    city: "Uppsala",
    bannerImageUrl: img("uppsala-university"),
    websiteUrl: "https://www.uu.se",
    description: "Scandinavia's oldest university, celebrated for medicine, pharmacy, and a thriving student-union culture.",
  },
  {
    slug: "stockholm-university",
    name: "Stockholm University",
    type: "INTERNATIONAL",
    country: "Sweden",
    city: "Stockholm",
    bannerImageUrl: img("stockholm-university"),
    websiteUrl: "https://www.su.se",
    description: "Major research university in the Swedish capital with strong natural science faculty and interdisciplinary programs.",
  },
  {
    slug: "chalmers-university-of-technology",
    name: "Chalmers University of Technology",
    type: "INTERNATIONAL",
    country: "Sweden",
    city: "Gothenburg",
    bannerImageUrl: img("chalmers-university"),
    websiteUrl: "https://www.chalmers.se",
    description: "Top Swedish technical university in Gothenburg partnering with global industry on sustainable technology challenges.",
  },
  {
    slug: "university-of-gothenburg",
    name: "University of Gothenburg",
    type: "INTERNATIONAL",
    country: "Sweden",
    city: "Gothenburg",
    bannerImageUrl: img("university-of-gothenburg"),
    websiteUrl: "https://www.gu.se",
    description: "Sweden's second-largest university with world-class oceanography, economics, and arts programs.",
  },
  {
    slug: "karolinska-institute",
    name: "Karolinska Institute",
    type: "INTERNATIONAL",
    country: "Sweden",
    city: "Stockholm",
    bannerImageUrl: img("karolinska-institute"),
    websiteUrl: "https://www.ki.se",
    description: "Sweden's only medical university and home of the Nobel Prize in Physiology or Medicine, globally leading in biomedical research.",
  },
  {
    slug: "linkoping-university",
    name: "Linköping University",
    type: "INTERNATIONAL",
    country: "Sweden",
    city: "Linköping",
    bannerImageUrl: img("linkoping-university"),
    websiteUrl: "https://liu.se",
    description: "Modern Swedish university excelling in applied IT, cognitive science, and industrial design.",
  },

  // ─── CHINA · INTERNATIONAL ─────────────────────────────────────
  {
    slug: "peking-university",
    name: "Peking University",
    type: "INTERNATIONAL",
    country: "China",
    city: "Beijing",
    bannerImageUrl: img("peking-university"),
    websiteUrl: "https://www.pku.edu.cn",
    description: "China's premier research university in Beijing, known for liberal arts, life sciences, and global academic impact.",
  },
  {
    slug: "tsinghua-university",
    name: "Tsinghua University",
    type: "INTERNATIONAL",
    country: "China",
    city: "Beijing",
    bannerImageUrl: img("tsinghua-university"),
    websiteUrl: "https://www.tsinghua.edu.cn",
    description: "China's top technical university producing world-class engineers, computer scientists, and architects since 1911.",
  },
  {
    slug: "fudan-university",
    name: "Fudan University",
    type: "INTERNATIONAL",
    country: "China",
    city: "Shanghai",
    bannerImageUrl: img("fudan-university"),
    websiteUrl: "https://www.fudan.edu.cn",
    description: "Elite comprehensive university in Shanghai renowned for medicine, economics, and international relations.",
  },
  {
    slug: "shanghai-jiao-tong-university",
    name: "Shanghai Jiao Tong University",
    type: "INTERNATIONAL",
    country: "China",
    city: "Shanghai",
    bannerImageUrl: img("sjtu-shanghai"),
    websiteUrl: "https://www.sjtu.edu.cn",
    description: "One of China's oldest and most prestigious universities, excelling in engineering, finance, and the life sciences.",
  },
  {
    slug: "zhejiang-university",
    name: "Zhejiang University",
    type: "INTERNATIONAL",
    country: "China",
    city: "Hangzhou",
    bannerImageUrl: img("zhejiang-university"),
    websiteUrl: "https://www.zju.edu.cn",
    description: "Comprehensive research university in Hangzhou with top-ranked programs in agriculture, materials, and computer science.",
  },
  {
    slug: "university-of-science-and-technology-of-china",
    name: "University of Science and Technology of China",
    type: "INTERNATIONAL",
    country: "China",
    city: "Hefei",
    bannerImageUrl: img("ustc-hefei"),
    websiteUrl: "https://www.ustc.edu.cn",
    description: "Elite STEM-focused university in Hefei under the Chinese Academy of Sciences, globally renowned for physics and AI research.",
  },
  {
    slug: "nankai-university",
    name: "Nankai University",
    type: "INTERNATIONAL",
    country: "China",
    city: "Tianjin",
    bannerImageUrl: img("nankai-university"),
    websiteUrl: "https://www.nankai.edu.cn",
    description: "Historic Chinese university in Tianjin with strong programs in economics, chemistry, and political science.",
  },
  {
    slug: "wuhan-university",
    name: "Wuhan University",
    type: "INTERNATIONAL",
    country: "China",
    city: "Wuhan",
    bannerImageUrl: img("wuhan-university"),
    websiteUrl: "https://www.whu.edu.cn",
    description: "Comprehensive university in Wuhan celebrated for its cherry-blossom campus, geomatics, and remote sensing programs.",
  },

  // ─── JAPAN · INTERNATIONAL ─────────────────────────────────────
  {
    slug: "university-of-tokyo",
    name: "University of Tokyo",
    type: "INTERNATIONAL",
    country: "Japan",
    city: "Tokyo",
    bannerImageUrl: img("university-of-tokyo"),
    websiteUrl: "https://www.u-tokyo.ac.jp",
    description: "Japan's most prestigious university consistently ranked Asia's best, excelling in engineering, science, and medicine.",
  },
  {
    slug: "kyoto-university",
    name: "Kyoto University",
    type: "INTERNATIONAL",
    country: "Japan",
    city: "Kyoto",
    bannerImageUrl: img("kyoto-university"),
    websiteUrl: "https://www.kyoto-u.ac.jp",
    description: "Academic crown jewel of ancient Kyoto, globally leading in chemistry, biology, and humanities with 18 Nobel laureates.",
  },
  {
    slug: "osaka-university",
    name: "Osaka University",
    type: "INTERNATIONAL",
    country: "Japan",
    city: "Osaka",
    bannerImageUrl: img("osaka-university"),
    websiteUrl: "https://www.osaka-u.ac.jp",
    description: "Top research university in Japan's second city, world-leading in medical science, laser physics, and robotics.",
  },
  {
    slug: "tohoku-university",
    name: "Tohoku University",
    type: "INTERNATIONAL",
    country: "Japan",
    city: "Sendai",
    bannerImageUrl: img("tohoku-university"),
    websiteUrl: "https://www.tohoku.ac.jp",
    description: "Leading Japanese research university famed for welcoming international students and pioneering materials science.",
  },
  {
    slug: "tokyo-institute-of-technology",
    name: "Tokyo Institute of Technology",
    type: "INTERNATIONAL",
    country: "Japan",
    city: "Tokyo",
    bannerImageUrl: img("tokyo-institute-technology"),
    websiteUrl: "https://www.titech.ac.jp",
    description: "Japan's top STEM-only university producing Nobel laureates and breakthrough research in materials and electronics.",
  },
  {
    slug: "nagoya-university",
    name: "Nagoya University",
    type: "INTERNATIONAL",
    country: "Japan",
    city: "Nagoya",
    bannerImageUrl: img("nagoya-university"),
    websiteUrl: "https://en.nagoya-u.ac.jp",
    description: "Leading Japanese university in Nagoya with exceptional chemistry, physics, and automotive engineering programs.",
  },
  {
    slug: "kyushu-university",
    name: "Kyushu University",
    type: "INTERNATIONAL",
    country: "Japan",
    city: "Fukuoka",
    bannerImageUrl: img("kyushu-university"),
    websiteUrl: "https://www.kyushu-u.ac.jp",
    description: "Major research university in Fukuoka with strengths in engineering, agriculture, and design innovation.",
  },
  {
    slug: "hokkaido-university",
    name: "Hokkaido University",
    type: "INTERNATIONAL",
    country: "Japan",
    city: "Sapporo",
    bannerImageUrl: img("hokkaido-university"),
    websiteUrl: "https://www.hokudai.ac.jp",
    description: "Japan's northernmost national university with world-class programs in agriculture, veterinary science, and low-temperature science.",
  },

  // ─── ITALY · INTERNATIONAL ─────────────────────────────────────
  {
    slug: "politecnico-di-milano",
    name: "Politecnico di Milano",
    type: "INTERNATIONAL",
    country: "Italy",
    city: "Milan",
    bannerImageUrl: img("politecnico-di-milano"),
    websiteUrl: "https://www.polimi.it",
    description: "Italy's top technical university in Milan, consistently the highest-ranked Italian institution for engineering and design.",
  },
  {
    slug: "university-of-bologna",
    name: "University of Bologna",
    type: "INTERNATIONAL",
    country: "Italy",
    city: "Bologna",
    bannerImageUrl: img("university-of-bologna"),
    websiteUrl: "https://www.unibo.it",
    description: "The world's oldest university, founded in 1088, offering thousands of programs across all disciplines.",
  },
  {
    slug: "sapienza-university-of-rome",
    name: "Sapienza University of Rome",
    type: "INTERNATIONAL",
    country: "Italy",
    city: "Rome",
    bannerImageUrl: img("sapienza-rome"),
    websiteUrl: "https://www.uniroma1.it",
    description: "One of Europe's largest universities in the Eternal City, excelling in medicine, law, and classical studies.",
  },
  {
    slug: "university-of-padua",
    name: "University of Padua",
    type: "INTERNATIONAL",
    country: "Italy",
    city: "Padua",
    bannerImageUrl: img("university-of-padua"),
    websiteUrl: "https://www.unipd.it",
    description: "Historic Italian university in Padua where Galileo Galilei taught, with outstanding science and medicine programs.",
  },
  {
    slug: "university-of-milan",
    name: "University of Milan",
    type: "INTERNATIONAL",
    country: "Italy",
    city: "Milan",
    bannerImageUrl: img("university-of-milan"),
    websiteUrl: "https://www.unimi.it",
    description: "Comprehensive university in Italy's fashion and finance capital, leading in life sciences, law, and humanities.",
  },
  {
    slug: "university-of-turin",
    name: "University of Turin",
    type: "INTERNATIONAL",
    country: "Italy",
    city: "Turin",
    bannerImageUrl: img("university-of-turin"),
    websiteUrl: "https://www.unito.it",
    description: "One of Italy's oldest universities in Piedmont, known for pharmaceutical sciences, law, and natural sciences.",
  },
  {
    slug: "university-of-naples-federico-ii",
    name: "University of Naples Federico II",
    type: "INTERNATIONAL",
    country: "Italy",
    city: "Naples",
    bannerImageUrl: img("naples-federico-ii"),
    websiteUrl: "https://www.unina.it",
    description: "Ancient Italian university founded by Emperor Frederick II in 1224, excelling in engineering and social sciences.",
  },
  {
    slug: "scuola-normale-superiore-pisa",
    name: "Scuola Normale Superiore di Pisa",
    type: "INTERNATIONAL",
    country: "Italy",
    city: "Pisa",
    bannerImageUrl: img("scuola-normale-pisa"),
    websiteUrl: "https://www.sns.it",
    description: "Elite Italian institution for research and advanced study, consistently placed among Europe's best small universities.",
  },

  // ─── SPAIN · INTERNATIONAL ─────────────────────────────────────
  {
    slug: "autonomous-university-of-madrid",
    name: "Autonomous University of Madrid",
    type: "INTERNATIONAL",
    country: "Spain",
    city: "Madrid",
    bannerImageUrl: img("uam-madrid"),
    websiteUrl: "https://www.uam.es",
    description: "Spain's leading research university, excelling in sciences, humanities, and economics in a green campus near Madrid.",
  },
  {
    slug: "university-of-barcelona",
    name: "University of Barcelona",
    type: "INTERNATIONAL",
    country: "Spain",
    city: "Barcelona",
    bannerImageUrl: img("university-of-barcelona"),
    websiteUrl: "https://www.ub.edu",
    description: "Spain's top university by research output, located in the vibrant cosmopolitan city of Barcelona.",
  },
  {
    slug: "complutense-university-of-madrid",
    name: "Complutense University of Madrid",
    type: "INTERNATIONAL",
    country: "Spain",
    city: "Madrid",
    bannerImageUrl: img("complutense-madrid"),
    websiteUrl: "https://www.ucm.es",
    description: "One of Europe's oldest universities in the Spanish capital, offering programs across all major academic disciplines.",
  },
  {
    slug: "pompeu-fabra-university",
    name: "Pompeu Fabra University",
    type: "INTERNATIONAL",
    country: "Spain",
    city: "Barcelona",
    bannerImageUrl: img("pompeu-fabra"),
    websiteUrl: "https://www.upf.edu",
    description: "Young, internationally renowned Barcelona university excelling in communication, economics, and biomedical research.",
  },
  {
    slug: "ie-university",
    name: "IE University",
    type: "INTERNATIONAL",
    country: "Spain",
    city: "Madrid",
    bannerImageUrl: img("ie-university-spain"),
    websiteUrl: "https://www.ie.edu",
    description: "Global business school and liberal arts university in Madrid ranked among the world's best for entrepreneurship.",
  },
  {
    slug: "university-of-valencia",
    name: "University of Valencia",
    type: "INTERNATIONAL",
    country: "Spain",
    city: "Valencia",
    bannerImageUrl: img("university-of-valencia"),
    websiteUrl: "https://www.uv.es",
    description: "One of Spain's oldest universities in the Mediterranean city of Valencia, strong in natural sciences and medicine.",
  },
  {
    slug: "university-of-salamanca",
    name: "University of Salamanca",
    type: "INTERNATIONAL",
    country: "Spain",
    city: "Salamanca",
    bannerImageUrl: img("university-of-salamanca"),
    websiteUrl: "https://www.usal.es",
    description: "Spain's oldest university founded in 1134, offering immersive study in law, humanities, and Spanish language.",
  },
  {
    slug: "carlos-iii-university-of-madrid",
    name: "Carlos III University of Madrid",
    type: "INTERNATIONAL",
    country: "Spain",
    city: "Madrid",
    bannerImageUrl: img("carlos-iii-madrid"),
    websiteUrl: "https://www.uc3m.es",
    description: "Young research university in Madrid ranked Spain's best in social sciences, economics, and law.",
  },
];

const programTemplates = [
  {
    slug: "bsc-in-computer-science",
    name: "BSc in Computer Science",
    level: "BACHELORS",
    discipline: "Computer Science",
    durationMonths: 48,
    intakeTerm: "Fall",
    tuitionAnnualUsd: 8000,
    minGpa: 3.2,
    minIelts: 6.0,
  },
  {
    slug: "msc-in-data-science",
    name: "MSc in Data Science",
    level: "MASTERS",
    discipline: "Data Science",
    durationMonths: 24,
    intakeTerm: "Fall",
    tuitionAnnualUsd: 15000,
    minGpa: 3.3,
    minIelts: 6.5,
  },
  {
    slug: "mba",
    name: "Master of Business Administration",
    level: "MASTERS",
    discipline: "Business Administration",
    durationMonths: 24,
    intakeTerm: "Spring",
    tuitionAnnualUsd: 18000,
    minGpa: 3.0,
    minIelts: 6.5,
  },
];

const scholarshipTemplates = [
  {
    slug: "global-merit-scholarship",
    title: "Global Merit Scholarship",
    type: "MERIT",
    amountType: "PARTIAL_TUITION",
    amountValue: 7000,
    currency: "USD",
    description:
      "Awarded to high-achieving students with outstanding academic records and leadership profile.",
    eligibilityCriteria: "Minimum GPA 3.5 and strong extracurricular profile.",
    deadlineOffsetDays: 60,
  },
  {
    slug: "future-leaders-scholarship",
    title: "Future Leaders Scholarship",
    type: "NEED_BASED",
    amountType: "PARTIAL_TUITION",
    amountValue: 5000,
    currency: "USD",
    description:
      "Supports students with demonstrated financial need and clear career goals.",
    eligibilityCriteria: "Need assessment plus admission offer.",
    deadlineOffsetDays: 45,
  },
  {
    slug: "research-excellence-award",
    title: "Research Excellence Award",
    type: "RESEARCH",
    amountType: "FIXED_AMOUNT",
    amountValue: 4000,
    currency: "USD",
    description:
      "For applicants with prior publications, conference papers, or strong research proposals.",
    eligibilityCriteria: "Research proposal and faculty recommendation required.",
    deadlineOffsetDays: 75,
  },
];

const newsTemplates = [
  {
    slug: "fall-intake-application-window-now-open",
    title: "Fall Intake Application Window Is Now Open",
    excerpt: "Apply early to improve your admission and scholarship chances.",
    content:
      "Universities have started accepting applications for the upcoming fall term. Students are encouraged to prepare documents early and submit before priority deadlines.",
    category: "ADMISSION",
    coverImageUrl:
      "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1400&q=80",
    daysAgo: 2,
  },
  {
    slug: "new-partnerships-expand-scholarship-opportunities",
    title: "New Partnerships Expand Scholarship Opportunities",
    excerpt: "International partners announced additional funding for selected programs.",
    content:
      "Multiple institutions announced collaboration programs that include scholarship funds, fee waivers, and mentorship support for international applicants.",
    category: "SCHOLARSHIP",
    coverImageUrl:
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1400&q=80",
    daysAgo: 4,
  },
  {
    slug: "student-visa-processing-updates-for-2026",
    title: "Student Visa Processing Updates for 2026",
    excerpt: "Recent updates may affect processing times for key study destinations.",
    content:
      "Applicants should monitor visa appointment and processing updates for their destination countries and maintain complete documentation for smoother outcomes.",
    category: "INTERNATIONAL",
    coverImageUrl:
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1400&q=80",
    daysAgo: 7,
  },
  {
    slug: "how-to-build-a-strong-university-shortlist",
    title: "How to Build a Strong University Shortlist",
    excerpt: "Balance ranking, budget, location, and program fit for better outcomes.",
    content:
      "A balanced shortlist should include aspirational, target, and safe universities while matching budget, test scores, and long-term goals.",
    category: "SYSTEM",
    coverImageUrl:
      "https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=1400&q=80",
    daysAgo: 10,
  },
];

function addDays(date, days) {
  const copy = new Date(date);
  copy.setDate(copy.getDate() + days);
  return copy;
}

async function upsertUniversities() {
  const map = new Map();

  for (const data of universities) {
    const university = await prisma.university.upsert({
      where: { slug: data.slug },
      update: {
        name: data.name,
        type: data.type,
        country: data.country,
        city: data.city,
        description: data.description,
        websiteUrl: data.websiteUrl,
        bannerImageUrl: data.bannerImageUrl,
        isActive: true,
      },
      create: {
        slug: data.slug,
        name: data.name,
        type: data.type,
        country: data.country,
        city: data.city,
        description: data.description,
        websiteUrl: data.websiteUrl,
        bannerImageUrl: data.bannerImageUrl,
        isActive: true,
      },
    });

    map.set(data.slug, university);
  }

  return map;
}

async function upsertPrograms(universityMap) {
  const programMap = new Map();

  for (const university of universities) {
    const universityRecord = universityMap.get(university.slug);
    if (!universityRecord) continue;

    for (const template of programTemplates) {
      const slug = `${template.slug}-${university.slug.slice(0, 10)}`;
      const intakeYear = new Date().getFullYear();
      const deadline = addDays(new Date(), 45);

      const program = await prisma.program.upsert({
        where: {
          universityId_slug: {
            universityId: universityRecord.id,
            slug,
          },
        },
        update: {
          name: template.name,
          level: template.level,
          discipline: template.discipline,
          durationMonths: template.durationMonths,
          intakeTerm: template.intakeTerm,
          intakeYear,
          applicationDeadline: deadline,
          tuitionAnnualUsd: template.tuitionAnnualUsd,
          minGpa: template.minGpa,
          minIelts: template.minIelts,
          isActive: true,
        },
        create: {
          universityId: universityRecord.id,
          slug,
          name: template.name,
          level: template.level,
          discipline: template.discipline,
          durationMonths: template.durationMonths,
          intakeTerm: template.intakeTerm,
          intakeYear,
          applicationDeadline: deadline,
          tuitionAnnualUsd: template.tuitionAnnualUsd,
          minGpa: template.minGpa,
          minIelts: template.minIelts,
          isActive: true,
        },
      });

      programMap.set(`${university.slug}:${template.slug}`, program);
    }
  }

  return programMap;
}

async function upsertScholarships(universityMap, programMap) {
  let counter = 0;
  const now = new Date();

  for (const university of universities) {
    const universityRecord = universityMap.get(university.slug);
    if (!universityRecord) continue;

    for (const template of scholarshipTemplates) {
      const programKey = `${university.slug}:${programTemplates[counter % programTemplates.length].slug}`;
      const programRecord = programMap.get(programKey);

      const slug = `${template.slug}-${university.slug.slice(0, 8)}`;

      await prisma.scholarship.upsert({
        where: { slug },
        update: {
          universityId: universityRecord.id,
          programId: programRecord?.id ?? null,
          title: `${university.name} ${template.title}`,
          type: template.type,
          amountType: template.amountType,
          amountValue: template.amountValue,
          currency: template.currency,
          description: template.description,
          eligibilityCriteria: template.eligibilityCriteria,
          deadline: addDays(now, template.deadlineOffsetDays),
          isActive: true,
        },
        create: {
          slug,
          universityId: universityRecord.id,
          programId: programRecord?.id ?? null,
          title: `${university.name} ${template.title}`,
          type: template.type,
          amountType: template.amountType,
          amountValue: template.amountValue,
          currency: template.currency,
          description: template.description,
          eligibilityCriteria: template.eligibilityCriteria,
          deadline: addDays(now, template.deadlineOffsetDays),
          isActive: true,
        },
      });

      counter += 1;
    }
  }
}

async function upsertNews(universityMap) {
  let universityIndex = 0;

  for (const template of newsTemplates) {
    const uni = universities[universityIndex % universities.length];
    const universityRecord = universityMap.get(uni.slug);

    await prisma.news.upsert({
      where: { slug: template.slug },
      update: {
        title: template.title,
        excerpt: template.excerpt,
        content: template.content,
        category: template.category,
        status: "PUBLISHED",
        coverImageUrl: template.coverImageUrl,
        publishedAt: addDays(new Date(), -template.daysAgo),
        universityId: universityRecord?.id ?? null,
      },
      create: {
        slug: template.slug,
        title: template.title,
        excerpt: template.excerpt,
        content: template.content,
        category: template.category,
        status: "PUBLISHED",
        coverImageUrl: template.coverImageUrl,
        publishedAt: addDays(new Date(), -template.daysAgo),
        universityId: universityRecord?.id ?? null,
      },
    });

    universityIndex += 1;
  }
}

async function main() {
  console.log("Starting seed...");

  const universityMap = await upsertUniversities();
  const programMap = await upsertPrograms(universityMap);
  await upsertScholarships(universityMap, programMap);
  await upsertNews(universityMap);

  const [universitiesCount, programsCount, scholarshipsCount, newsCount] = await Promise.all([
    prisma.university.count(),
    prisma.program.count(),
    prisma.scholarship.count(),
    prisma.news.count(),
  ]);

  console.log("Seed complete.");
  console.log(
    JSON.stringify(
      {
        universities: universitiesCount,
        programs: programsCount,
        scholarships: scholarshipsCount,
        news: newsCount,
      },
      null,
      2,
    ),
  );
}

main()
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
